### ISSUE TITLE
Error: Could not recognize TS format during slice!

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/boilerplate#343]
```
npx scrypt-cli@latest p btccontracts
cd btccontracts
npm i
npm t
```
gives
```
> btccontracts@0.1.0 pretest
> npm run build && npm run compile


> btccontracts@0.1.0 prebuild
> npm run clean


> btccontracts@0.1.0 clean
> rimraf scrypt.index.json && rimraf dist && rimraf artifacts


> btccontracts@0.1.0 build
> tsc


> btccontracts@0.1.0 compile
> npx scrypt-cli compile

⠴ Building TS...
/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/slice/ts55.js:42
            throw module_slice_1.ModuleSlice.createError();
            ^

Error: Could not recognize TS format during slice!
    at Object.ModuleSlice.createError (/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/slice/module-slice.js:30:40)
    at sliceTs55 (/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/slice/ts55.js:42:46)
    at sliceModule (/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/slice/module-slice.js:24:33)
    at getModuleSource (/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/module/module-source.js:12:130)
    at Object.getUnpatchedSource (/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/module/ts-module.js:72:56)
    at patchModule (/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/patch/patch-module.js:40:43)
    at getPatchedSource (/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/patch/get-patched-source.js:48:52)
    at getLiveModule (/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/module/get-live-module.js:21:62)
    at Object.<anonymous> (/Users/xhliu/projects/btc/btccontracts/node_modules/ts-patch/compiler/tsc.js:11:26)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
✖ Building TS
ERROR: Building TS failed!
Please modify your code or `tsconfig-scryptTS.json` according to the error message output during BUILDING.
```

**Comment by zhfnjust** [comment]
Now BTC developers use the new CLI and cannot reproduce the problem
