### ISSUE TITLE
Compile Error: stack should have at least 1 element(s) when execute OP_DROP, BUT without the OP

### ISSUE THREAD

**Issue by baryon** [sCrypt-Inc/boilerplate#82]
When I compile  some code, got an error. it shows  "stack should have at least 1 element(s) when execute OP_DROP", but there is not OP_DROP in the code.

```
contract MultiSignBug {
  public function unlock(bytes p0, bytes p1) {
    asm {
      OP_0
      OP_TOALTSTACK
      OP_IF
        OP_DUP
        OP_HASH160
        dd2d89bb9f64cbdf4139ff0e23c4813124af85e6
        OP_EQUALVERIFY
        OP_CHECKSIGVERIFY
        OP_FROMALTSTACK
        OP_1ADD
        OP_TOALTSTACK
      OP_ENDIF
      OP_IF
        OP_DUP
        OP_HASH160
        aef82c0ef3f0c1d867e12b64e9e8d2ebb983dc81
        OP_EQUALVERIFY
        OP_CHECKSIGVERIFY
        OP_FROMALTSTACK
        OP_1ADD
        OP_TOALTSTACK
      OP_ENDIF
      OP_2
      OP_FROMALTSTACK
      OP_GREATERTHANOREQUAL
    }
  }
}
```

```
Compiling contract /Users/lilong/Works/scrypt-sv/boilerplate/contracts/MultiSignBug.scrypt ...
scryptc: stack should have at least 1 element(s) when execute OP_DROP
CallStack (from HasCallStack):
  error, called at library/IR.hs:844:7 in scrypt-0.4.0-6NbrB0JZAjUF7YaB6RhLSB:IR
Error: Command failed: /Users/lilong/.vscode/extensions/bsv-scrypt.scrypt-0.7.1/compiler/scryptc/mac/scryptc compile --asm --ast --debug  -r -o "/Users/lilong/Works/scrypt-sv/boilerplate/deployments/fixture/autoGen" 
scryptc: stack should have at least 1 element(s) when execute OP_DROP
CallStack (from HasCallStack):
  error, called at library/IR.hs:844:7 in scrypt-0.4.0-6NbrB0JZAjUF7YaB6RhLSB:IR

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.compile (/Users/lilong/Works/scrypt-sv/boilerplate/node_modules/scryptlib/dist/compilerWrapper.js:53:38)
    at compileContract (/Users/lilong/Works/scrypt-sv/boilerplate/node_modules/scryptlib/dist/utils.js:611:38)
    at compileContract (/Users/lilong/Works/scrypt-sv/boilerplate/helper.js:149:18)
    at compile_for (/Users/lilong/Works/scrypt-sv/boilerplate/watcher.js:12:7)
    at /Users/lilong/Works/scrypt-sv/boilerplate/watcher.js:44:9
    at Array.forEach (<anonymous>)
    at /Users/lilong/Works/scrypt-sv/boilerplate/watcher.js:43:22
    at /Users/lilong/Works/scrypt-sv/boilerplate/node_modules/watch/main.js:112:5 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 73 63 72 79 70 74 63 3a 20 73 74 61 63 6b 20 73 68 6f 75 6c 64 20 68 61 76 65 20 61 74 20 6c 65 61 73 74 20 31 20 65 6c 65 6d 65 6e 74 28 73 29 20 77 ... 132 more bytes>
  ],
  pid: 32398,
  stdout: <Buffer >,
  stderr: <Buffer 73 63 72 79 70 74 63 3a 20 73 74 61 63 6b 20 73 68 6f 75 6c 64 20 68 61 76 65 20 61 74 20 6c 65 61 73 74 20 31 20 65 6c 65 6d 65 6e 74 28 73 29 20 77 ... 132 more bytes>
}
```

**Comment by xhliu** [comment]
When OP_CHECKSIGVERIFY is run, there is only 1 element on the stack. That's why it fails. You probably mean OP_EQUAL, not OP_EQUALVERIFY before it.

![image](https://user-images.githubusercontent.com/1017252/113523025-2aa53f00-955a-11eb-84b0-7df6c1b691c6.png)


Good catch on the error message. Will make it more clearer.
